### ISSUE TITLE
Projection parameter matrices in MultiHeadAttention are missing?

### ISSUE THREAD

**Issue by ArvinZhuang** [ULTR-Community/ULTRA#12]
In SetRank.py line52 - 54 the q,k,v linear projection layer are commented out, I understand that this is to meet the permutation-equivariant requirement, but should we make a single dense layer and pass all q,k,v to it so that can get three identical projection matrices rather than just using identical inputs?

**Comment by Taosheng-ty** [comment]
Thanks, what you mentioned is correct. We might test it later.

**Comment by Taosheng-ty** [comment]
> 
> 
> In SetRank.py line52 - 54 the q,k,v linear projection layer are commented out, I understand that this is to meet the permutation-equivariant requirement, but should we make a single dense layer and pass all q,k,v to it so that can get three identical projection matrices rather than just using identical inputs?

Actually, there are already some dense layers between line 106 and line 114.  And the ranking performance doesn't improve. Thus, I decide to keep the original version.

**Comment by ArvinZhuang** [comment]
right, I see, thanks for the clarification.
