### ISSUE TITLE
./example/MSLR_WEB10k/offline_exp_pipeline.sh execution error

### ISSUE THREAD

**Issue by lxldyxhao** [ULTR-Community/ULTRA#14]
I am studying the usage of ULTRA, and I find the line at:
https://github.com/ULTR-Community/ULTRA/blob/master/example/MSLR_WEB10k/offline_exp_pipeline.sh#L7
cause a problem because when bash entered ../../, it is not possible to run python scripts behind the bash.

I delete this line and it runs correctly. Is it a problem, or just I run it in a wrong dir?

**Comment by QingyaoAi** [comment]
Thanks for pointing it out. The script was originally tested from ./example/MSLR_WEB10k/. Could you try that again and see whether it works?

**Comment by lxldyxhao** [comment]
Thanks for your reply. I got it.
I run it in Ultra dir, because README.md says that the toy script should run like this:
`bash example/toy/offline_exp_pipeline.sh`
