### ISSUE TITLE
Tensorboard stuck at "namespace hierarchy: finding similar subgraphs stuck"

### ISSUE THREAD

**Issue by lxldyxhao** [ULTR-Community/ULTRA#15]
When I try to open the computational graph on tensorboard, It always stuck at this line:
"namespace hierarchy: finding similar subgraphs stuck"
After a few minutes' wating, the graph successful shows only when I use DNN model,  which may because of the simple structure of this model. But others still unshown.
How can I improve this problem?  Thank you very much ! !

**Comment by QingyaoAi** [comment]
Thanks for pointing it out! Could you please attach the command you used so that we could reproduce the problem?
