### ISSUE TITLE
Getting import error when running the toy example

### ISSUE THREAD

**Issue by zhenduow** [ULTR-Community/ULTRA#16]
Hi,

I get this error when I follow the instructions and run the toy example:

I am using macOS, python version 3.6.13, tensor flow==1.8.0.

/Users/xxx/anaconda3/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/xxx/anaconda3/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/xxx/anaconda3/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:521: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/xxx/anaconda3/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:522: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/Users/xxx/anaconda3/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/Users/xxx/anaconda3/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "main.py", line 21, in <module>
    import ultra
  File "/Users/xxx/ULTRA/ultra/__init__.py", line 4, in <module>
    from . import learning_algorithm
  File "/Users/xxx/ULTRA/ultra/learning_algorithm/__init__.py", line 4, in <module>
    from .dla import *
  File "/Users/xxx/ULTRA/ultra/learning_algorithm/dla.py", line 24, in <module>
    from tensorflow import dtypes
ImportError: cannot import name 'dtypes'

Can you please give some advice? Thank you very much!

**Comment by QingyaoAi** [comment]
It seems to be a problem with the TensorFlow version you used. Please try the virtualenv option and install tensorflow from the scratch.

**Comment by zhenduow** [comment]
Yes, you are right, I created a new venv and installed tensorflow==1.15.0. Then it worked. Thank you!
