### ISSUE TITLE
`selection_bias_cutoff` setting for Multileave Gradient Descent (MGD) algorithm 

### ISSUE THREAD

**Issue by rowedenny** [ULTR-Community/ULTRA#18]
I would like to get the letor_features out of the top 10 documents. thus I follow the implementation of I MGD, but I had difficulty setting parameters, specifically for `selection_bias_cutoff `.  

If I understand correctly, MGC will first fetch the prediction for all docs under a query, as 
https://github.com/ULTR-Community/ULTRA/blob/master/ultra/learning_algorithm/mgd.py#L85

however, as in main.py, we have,
```
exp_settings['selection_bias_cutoff'] = min(exp_settings['selection_bias_cutoff'], exp_settings['max_candidate_num'])
```
when the model is initialized, we have,
```
self.rank_list_size = self.exp_settings['selection_bias_cutoff']
```

and when creating the input_feed, we have,
```
self.rank_list_size = model.rank_list_size


for x in range(self.rank_list_size):
    if data_set.initial_list[i][x] >= 0:
        letor_features.append(
            data_set.features[data_set.initial_list[i][x]])
```

Therefore, if we set argument `selection_bias_cutoff = 10` as usual, then `letor_features` in one input feed will always be size [?, selection_bias_cutoff] 

Then when we try to fetch the features from `docid_inputs`,  the key out of the top 10 will be invalid. Hence, `        self.output = tf.concat(
            self.get_ranking_scores(
                self.docid_inputs,
                is_training=self.is_training,
                scope='ranking_model'),
            1)` will trigger an error.

However, we cannot simply set `selection_bias_cutoff = 0`, since:
1) it will show more than 10 document to the user and generates click
2) the ranking model will train the model with more than top 10 documents as well.

I am wondering if there is any quick way to circumvent this issue, or if I had any misunderstanding of the pipeline?

**Comment by QingyaoAi** [comment]
As you can see in the code you have attached, the shape of letor_features is the [?, feature_size], not [?, selection_bias_cutoff]. Here we use letor_features to store and index all the feature vectors used in the batch. It's not the actual ranked lists.

**Comment by rowedenny** [comment]
Thanks for the quick reponse.

However, as we can see:
```
for x in range(self.rank_list_size):
    if data_set.initial_list[i][x] >= 0:
        letor_features.append(
            data_set.features[data_set.initial_list[i][x]])
```
the `letor_feature` will be [rank_list_size, feature_size]. So it only stores features vectors until `selection_bias_cutoff`.

**Comment by rowedenny** [comment]
I got it.

For MGD, we shall refer to the config as **online_setting**, in which the input_feed is `StochasticOnlineSimulationFeed`. 
Then, the letor_features are fetched for `max_candidate_num`, as you explained previously, in the following code snippet:
```
    def prepare_true_labels_with_index(
            self, data_set, index, docid_inputs, letor_features, labels, check_validation=False):
        i = index
        # Generate label list.
        label_list = [
            0 if data_set.initial_list[i][x] < 0 else data_set.labels[i][x] for x in range(
                self.max_candidate_num)]

        # Check if data is valid
        if check_validation and sum(label_list) == 0:
            return
        base = len(letor_features)
        for x in range(self.max_candidate_num):
            if data_set.initial_list[i][x] >= 0:
                letor_features.append(
                    data_set.features[data_set.initial_list[i][x]])
        docid_inputs.append(list([-1 if data_set.initial_list[i][x]
                                  < 0 else base + x for x in range(self.max_candidate_num)]))
        labels.append(label_list)
```
