### ISSUE TITLE
Specifying the number of query sessions

### ISSUE THREAD

**Issue by shashankg7** [ULTR-Community/ULTRA#22]
Hi, 

I am trying to understand the workflow of the package for some experiments on IPS. 

I was wondering if we can specify the number of query sessions to be simulated for click simulation? 

Context: I want to try training IPS on different sizes of simulated log data. 

I tried reading the offline exp. bash script from example folders, but couldn't figure out if we can do so. Apologies if this is something obvious I am missing from the documentation. 

Thanks.

**Comment by QingyaoAi** [comment]
You can check about the input_feed methods. The click simulation feed we provided now only supports random query sampling. If you want to define the number of sessions to be sampled for each query, you can either create a click log offline and use the direct_input_feed or create a new input_feed by yourself.

**Comment by shashankg7** [comment]
Thanks for your reply. I'll close this issue.
